# Generated by Django 3.0.8 on 2020-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(blank=True, db_column='No', null=True)),
                ('item_code', models.BigIntegerField(blank=True, null=True)),
                ('itme_name', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.DateTimeField()),
                ('con', models.CharField(blank=True, max_length=10, null=True)),
                ('item_kind', models.CharField(blank=True, max_length=5, null=True)),
                ('soter', models.CharField(blank=True, max_length=5, null=True)),
                ('input', models.IntegerField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=5, null=True)),
                ('bus_num', models.CharField(blank=True, max_length=5, null=True)),
                ('order_part', models.CharField(blank=True, max_length=5, null=True)),
                ('cmpy_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cmpy_name', models.CharField(blank=True, max_length=300, null=True)),
                ('order_value', models.IntegerField(blank=True, null=True)),
                ('ordered_value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('order_price', models.IntegerField(blank=True, null=True)),
                ('delivery_part', models.CharField(blank=True, max_length=5, null=True)),
                ('ett', models.CharField(blank=True, max_length=300, null=True)),
                ('ordered_num', models.BigIntegerField(blank=True, null=True)),
                ('ordered_item_num', models.IntegerField(blank=True, db_column='ordered_ITEM_num', null=True)),
                ('order_num', models.BigIntegerField(blank=True, null=True)),
                ('order_item_num', models.IntegerField(blank=True, db_column='order_ITEM_num', null=True)),
                ('delivery_cmpy', models.CharField(blank=True, max_length=5, null=True)),
                ('delivery_num', models.CharField(blank=True, max_length=5, null=True)),
                ('factory_num', models.CharField(blank=True, max_length=5, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'order_paper',
                'managed': False,
            },
        ),
    ]
