# Generated by Django 3.0.8 on 2020-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_orderpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('item_code', models.BigIntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=600, null=True)),
                ('item_nick_name', models.CharField(blank=True, max_length=300, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('pb', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
    ]
