# Generated by Django 3.0.8 on 2020-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('item_code', models.BigIntegerField(unique=True)),
                ('item_name', models.CharField(blank=True, max_length=600, null=True)),
                ('item_nick_name', models.CharField(blank=True, max_length=350, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('pb', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
